spring:
  ai:
    openai:
      api-key: sk-mock-dev-key

ai:
  enabled: false

fhir:
  server:
    url: https://snowstorm-training.snomedtools.org/fhir

snomed:
  branch: MAIN
  language: sv
  language-refset: 
  fallback-to-english: true
